const demo = [
['2024','ЕГЭ','Русский язык',68.71,68.25,99,63,234,''],['2025','ЕГЭ','Русский язык',62.25,66.47,112,172,288,''],['2026','ЕГЭ','Русский язык',71.97,69.23,145,64,283,''],
['2024','ЕГЭ','Математика профильная',67.88,69.58,50,123,331,''],['2025','ЕГЭ','Математика профильная',67.37,70.04,68,192,332,''],['2026','ЕГЭ','Математика профильная',73.50,74.36,101,79,136,''],
['2024','ЕГЭ','Информатика',73.33,65.41,18,19,258,''],['2025','ЕГЭ','Информатика',73.91,69.58,32,48,203,''],['2026','ЕГЭ','Информатика',75.04,72.67,50,72,208,''],
['2024','ЕГЭ','Литература',69.46,71.71,13,159,240,''],['2025','ЕГЭ','Литература',68.00,74.20,3,'','',''],['2026','ЕГЭ','Литература',82.33,75.26,12,39,196,''],
['2024','ЕГЭ','Английский язык',73.52,72.96,42,124,244,''],['2025','ЕГЭ','Английский язык',75.37,68.99,19,42,253,''],['2026','ЕГЭ','Английский язык',73.18,74.27,56,144,225,''],
['2024','ЕГЭ','История',75.00,65.52,11,26,274,''],['2025','ЕГЭ','История',63.83,63.33,6,'','',''],['2026','ЕГЭ','История',65.67,68.57,12,142,223,''],
['2024','ЕГЭ','Обществознание',62.70,61.45,40,121,396,''],['2025','ЕГЭ','Обществознание',57.28,60.24,36,284,386,''],['2026','ЕГЭ','Обществознание',63.09,62.96,64,159,344,''],
['2024','ЕГЭ','География',65.33,61.93,'','','',''],['2025','ЕГЭ','География',52.91,61.32,11,22,32,''],['2026','ЕГЭ','География',61.00,62.51,4,'','',''],
['2024','ЕГЭ','Физика',65.13,72.43,'','','',''],['2025','ЕГЭ','Физика',61.56,69.95,16,212,252,''],['2026','ЕГЭ','Физика',70.32,76.59,28,193,270,''],
['2024','ЕГЭ','Химия',55.33,68.21,'','','',''],['2025','ЕГЭ','Химия',62.13,68.98,8,'','',''],['2026','ЕГЭ','Химия',70.80,72.02,5,'','',''],
['2024','ЕГЭ','Биология',48.44,61.31,10,244,263,''],['2025','ЕГЭ','Биология',58.50,62.71,18,150,254,''],['2026','ЕГЭ','Биология',55.25,67.11,12,217,242,'']
,
['2024','ОГЭ','Русский язык',4.12,null,191,null,null,''],['2025','ОГЭ','Русский язык',3.95,null,154,null,null,''],['2026','ОГЭ','Русский язык',4.02,null,171,null,null,''],
['2024','ОГЭ','Математика',4.19,null,191,null,null,''],['2025','ОГЭ','Математика',3.80,null,155,null,null,''],['2026','ОГЭ','Математика',4.08,null,171,null,null,''],
['2024','ОГЭ','Физика',4.03,null,31,null,null,''],['2025','ОГЭ','Физика',3.91,null,22,null,null,''],['2026','ОГЭ','Физика',4.00,null,22,null,null,''],
['2024','ОГЭ','Информатика',4.31,null,70,null,null,''],['2025','ОГЭ','Информатика',4.77,null,35,null,null,''],['2026','ОГЭ','Информатика',4.61,null,63,null,null,''],
['2024','ОГЭ','Химия',4.11,null,19,null,null,''],['2025','ОГЭ','Химия',4.55,null,11,null,null,''],['2026','ОГЭ','Химия',4.14,null,9,null,null,''],
['2024','ОГЭ','Биология',4.28,null,36,null,null,''],['2025','ОГЭ','Биология',4.10,null,20,null,null,''],['2026','ОГЭ','Биология',3.83,null,20,null,null,''],
['2024','ОГЭ','География',3.72,null,18,null,null,''],['2025','ОГЭ','География',4.22,null,9,null,null,''],['2026','ОГЭ','География',4.00,null,8,null,null,''],
['2024','ОГЭ','Литература',4.80,null,10,null,null,''],['2025','ОГЭ','Литература',4.88,null,8,null,null,''],['2026','ОГЭ','Литература',4.82,null,8,null,null,''],
['2024','ОГЭ','История',4.14,null,5,null,null,''],['2025','ОГЭ','История',3.53,null,3,null,null,''],['2026','ОГЭ','История',3.60,null,5,null,null,''],
['2024','ОГЭ','Обществознание',4.13,null,104,null,null,''],['2025','ОГЭ','Обществознание',3.86,null,58,null,null,''],['2026','ОГЭ','Обществознание',4.03,null,61,null,null,''],
['2024','ОГЭ','Английский язык',4.59,null,86,null,null,''],['2025','ОГЭ','Английский язык',4.80,null,55,null,null,''],['2026','ОГЭ','Английский язык',4.83,null,60,null,null,'']
].map(([year,exam,subject,school,city,participants,rank,total,teacher])=>({year,exam,subject,school:num(school),city:num(city),participants:num(participants),rank:num(rank),total:num(total),teacher}));

const topicAnalytics={
'Английский язык':{deficits:[['Языковое оформление текста',29],['Социокультурные знания и умения',67],['Грамматическая сторона речи',71],['Письменная речь',74],['Лексическая сторона речи',76]],success:[['Аудирование с пониманием запрашиваемой информации',100],['Организация текста',100],['Чтение с пониманием запрашиваемой информации',97],['Письменная речь',91],['Грамматика и лексика',90]]},
'Русский язык':{deficits:[['Фонетический анализ слова',0],['Синтаксический анализ предложения',7],['Распознавание орфограммы',12],['Части речи и их правописание',14],['Соблюдение орфографических норм',19]],success:[['Сопоставление предложений',96],['Соблюдение орфографических норм',91],['Подбор антонима',91],['Работа с текстом и смысловой анализ',91],['Распознавание слова по лексическому значению',90]]},
'Биология':{deficits:[['Строение и жизнедеятельность животного организма',10],['Анализ данных и развёрнутые задачи',28],['Эволюция и экология',30],['Признаки классов членистоногих и хордовых',32],['Систематика растений и работа с микроскопом',32]],success:[['Методы научного познания: расчёт количества нуклеотидов',89],['Систематика растений и биологическая информация',88],['Человек и здоровье',87],['Биология как наука. Клетка',82],['Работа с биологической информацией',80]]},
'География':{deficits:[['Современная политическая карта мира',15],['Литосфера и применение понятий',19],['Сравнение климата отдельных территорий',28],['Практические расчёты и анализ данных',29],['Следствия движения Земли',33]],success:[['Оболочки Земли, материки и океаны',93],['Крайние точки и береговая линия России',90],['План местности и условные обозначения',82],['Мировое хозяйство',81],['Практические расчёты и анализ данных',70]]},
'Физика':{deficits:[['Эксперимент в физике',0],['Исследование зависимостей прямыми измерениями',0],['Описание тепловых свойств и явлений',0],['Описание электрических свойств и процессов',0],['Всемирное тяготение и движение небесных тел',4]],success:[['Механика',95],['Тепловые явления',85],['Электричество и магнетизм',85],['Косвенные измерения физических величин',78],['Оптика, атомная и квантовая физика',75]]},
'Химия':{deficits:[['Расчёты с использованием массовой доли вещества',0],['Масса растворённого вещества и растворителя',0],['Свойства спиртов и фенолов',11],['Атомы, молекулы и химические элементы',33],['Определение кислот и щелочей индикаторами',37]],success:[['Чистые вещества и смеси',100],['Выявление веществ в составе смесей',100],['Физические и химические свойства веществ',100],['Химические реакции и физические явления',100],['Расчёт молярной массы по формуле',100]]},
'Обществознание':{deficits:[['Классификация понятий социальной действительности',20],['Классификация издержек производства',30],['Анализ изображений и формулирование вывода',32],['Решение практических задач',34],['Работа с таблицами',34]],success:[['Формы духовной культуры',100],['Социальные отношения',95],['Экономика',94],['Безопасное поведение в интернете',93],['Информационная культура и безопасность',84]]},
'История':{deficits:[['Последовательность событий и процессов XVIII века',0],['Описание памятников материальной и художественной культуры',0],['Исторические объекты на карте и их местоположение',38],['Контекстная информация при работе с историческими источниками XVI–XVII веков',49],['Причинно-следственные связи и развёрнутый ответ',56]],success:[['Анализ визуальных источников по истории XVIII века',100],['Анализ визуальных источников и признаков исторических процессов',100],['Культура, быт и нравы народов эпохи Средневековья',93],['История России: процессы и личности',93],['Причинно-следственные связи и развёрнутый ответ',56]]},
'Литература':{deficits:[['Стихотворный размер и тип рифмовки',35],['Мотив и тема лирического произведения',50],['Определение темы лирического произведения',50],['Теоретико-литературные понятия',55],['Названия лирических произведений по фрагментам',58]],success:[['Характеристика героя эпического или драматического произведения',100],['Анализ лирики',96],['Тема поэтического произведения',90],['Контекстуальное значение слова в художественном произведении',90],['Сочинение и критерии письменной речи',88]]},
'Математика':{deficits:[['Задачи с параметром',2.6],['Площадь трапеции',4],['Функция по графику',5],['Расстояние от точки до плоскости',10.7],['Углы в треугольнике',11.6]],success:[['Вероятность и статистика, 7 класс',73.8],['Математика, 5 класс',72.5],['Вероятность и статистика, 8 класс',55.8],['Вероятность и статистика, 10 класс',51.5],['Геометрия, 8 класс',50.1]]},
'Математика профильная':{deficits:[['Задача с параметром',2.6],['Площадь трапеции',4],['Функция по графику',5],['Расстояние от точки до плоскости',10.7],['Углы в треугольнике',11.6]],success:[['Вероятность и статистика, 7 класс',73.8],['Математика, 5 класс',72.5],['Вероятность и статистика, 8 класс',55.8],['Вероятность и статистика, 10 класс',51.5],['Геометрия, 8 класс',50.1]]},
'Информатика':{deficits:[['Алфавитный подход к измерению информации',13],['Табличные величины: массивы',17],['Представление чисел в памяти компьютера',30],['Адресация в сети Интернет',48],['Равномерные и неравномерные коды. Условие Фано',48]],success:[['Системы счисления и перевод чисел',74],['Исходные данные для получения результата алгоритма',74],['Анализ записи чисел в позиционной системе счисления',74],['Результаты работы простейших алгоритмов',70],['Таблицы истинности логических выражений',61]]}
};

const topicGrades={
'Фонетический анализ слова':'5 класс','Синтаксический анализ предложения':'5–9 классы','Распознавание орфограммы':'5–9 классы','Части речи и их правописание':'5–7 классы','Соблюдение орфографических норм':'5–11 классы','Сопоставление предложений':'5–9 классы','Подбор антонима':'5–6 классы','Работа с текстом и смысловой анализ':'5–11 классы','Распознавание слова по лексическому значению':'5–9 классы',
'Строение и жизнедеятельность животного организма':'8 класс','Анализ данных и развёрнутые задачи':'5–11 классы','Эволюция и экология':'9, 11 классы','Признаки классов членистоногих и хордовых':'8 класс','Систематика растений и работа с микроскопом':'6–7 классы','Методы научного познания: расчёт количества нуклеотидов':'10 класс','Систематика растений и биологическая информация':'6–7 классы','Человек и здоровье':'9 класс','Биология как наука. Клетка':'5, 10 классы','Работа с биологической информацией':'5–11 классы',
'Современная политическая карта мира':'7 класс','Литосфера и применение понятий':'5–6 классы','Сравнение климата отдельных территорий':'7–8 классы','Практические расчёты и анализ данных':'5–11 классы','Следствия движения Земли':'5 класс','Оболочки Земли, материки и океаны':'5–7 классы','Крайние точки и береговая линия России':'8 класс','План местности и условные обозначения':'5–6 классы','Мировое хозяйство':'9 класс',
'Эксперимент в физике':'7–11 классы','Исследование зависимостей прямыми измерениями':'7–9 классы','Описание тепловых свойств и явлений':'8 класс','Описание электрических свойств и процессов':'8 класс','Всемирное тяготение и движение небесных тел':'9, 11 классы','Механика':'7, 9–11 классы','Тепловые явления':'8, 10 классы','Электричество и магнетизм':'8, 10–11 классы','Косвенные измерения физических величин':'7–11 классы','Оптика, атомная и квантовая физика':'9, 11 классы',
'Расчёты с использованием массовой доли вещества':'8–9 классы','Масса растворённого вещества и растворителя':'8 класс','Свойства спиртов и фенолов':'10 класс','Атомы, молекулы и химические элементы':'8 класс','Определение кислот и щелочей индикаторами':'8 класс','Чистые вещества и смеси':'8 класс','Выявление веществ в составе смесей':'8 класс','Физические и химические свойства веществ':'8 класс','Химические реакции и физические явления':'8 класс','Расчёт молярной массы по формуле':'8 класс',
'Классификация понятий социальной действительности':'6–11 классы','Классификация издержек производства':'8, 11 классы','Анализ изображений и формулирование вывода':'6–11 классы','Решение практических задач':'6–11 классы','Работа с таблицами':'6–11 классы','Формы духовной культуры':'6–11 классы','Социальные отношения':'8–11 классы','Экономика':'7–11 классы','Безопасное поведение в интернете':'6–9 классы','Информационная культура и безопасность':'6–9 классы',
'Последовательность событий и процессов XVIII века':'8 класс','Описание памятников материальной и художественной культуры':'5–11 классы','Исторические объекты на карте и их местоположение':'5–11 классы','Контекстная информация при работе с историческими источниками XVI–XVII веков':'7 класс','Причинно-следственные связи и развёрнутый ответ':'5–11 классы','Анализ визуальных источников по истории XVIII века':'8 класс','Анализ визуальных источников и признаков исторических процессов':'5–11 классы','Культура, быт и нравы народов эпохи Средневековья':'6 класс','История России: процессы и личности':'6–11 классы',
'Стихотворный размер и тип рифмовки':'5–9 классы','Мотив и тема лирического произведения':'5–11 классы','Определение темы лирического произведения':'5–11 классы','Теоретико-литературные понятия':'5–11 классы','Названия лирических произведений по фрагментам':'5–11 классы','Характеристика героя эпического или драматического произведения':'5–11 классы','Анализ лирики':'5–11 классы','Тема поэтического произведения':'5–11 классы','Контекстуальное значение слова в художественном произведении':'5–11 классы','Сочинение и критерии письменной речи':'5–11 классы',
'Задачи с параметром':'9–11 классы','Задача с параметром':'9–11 классы','Площадь трапеции':'8 класс','Функция по графику':'7–11 классы','Расстояние от точки до плоскости':'10–11 классы','Углы в треугольнике':'7 класс',
'Алфавитный подход к измерению информации':'7 класс','Табличные величины: массивы':'8–9 классы','Представление чисел в памяти компьютера':'8–10 классы','Адресация в сети Интернет':'8–9 классы','Равномерные и неравномерные коды. Условие Фано':'8–10 классы','Системы счисления и перевод чисел':'8 класс','Исходные данные для получения результата алгоритма':'8–11 классы','Анализ записи чисел в позиционной системе счисления':'8–10 классы','Результаты работы простейших алгоритмов':'8–9 классы','Таблицы истинности логических выражений':'8–9 классы'
};
const topicDefaults={'Английский язык':'5–11 классы','Русский язык':'5–11 классы'};
const uniqueParticipants={'ЕГЭ':{'2024':99,'2025':112,'2026':149},'ОГЭ':{'2024':191,'2025':155,'2026':171}};
const taskEssences={
'ЕГЭ|Математика профильная':{1:'Планиметрия: простейшая геометрическая задача',2:'Векторы и координаты',3:'Стереометрия: простейшая задача',4:'Классическая вероятность',5:'Вероятность сложного события',6:'Решение уравнения',7:'Вычисления и преобразования выражений',8:'Производная и исследование функции',9:'Прикладная текстовая задача',10:'Графики и свойства функций',11:'Текстовая задача на составление уравнения',12:'Наибольшее и наименьшее значение функции',13:'Уравнение с отбором корней',14:'Стереометрическая задача',15:'Неравенство',16:'Финансовая математика',17:'Планиметрическая задача',18:'Задача с параметром',19:'Числа и их свойства'},
'ОГЭ|Математика':{1:'Практическая задача по условию',2:'Практические расчёты',3:'Работа с таблицей или схемой',4:'Зависимости между величинами',5:'Практическая задача повышенной сложности',6:'Числа и вычисления',7:'Числовая прямая',8:'Алгебраические выражения',9:'Уравнения',10:'Вероятность',11:'Графики функций',12:'Расчёты по формулам',13:'Неравенства',14:'Последовательности и прогрессии',15:'Геометрия треугольника',16:'Окружность и круг',17:'Четырёхугольники',18:'Фигуры на клетчатой решётке',19:'Анализ геометрических утверждений',20:'Алгебраическая задача с развёрнутым решением',21:'Текстовая задача',22:'Построение или исследование графика',23:'Расчётная задача по геометрии',24:'Доказательство в геометрии',25:'Геометрическая задача высокой сложности'},
'ЕГЭ|Русский язык':{1:'Логико-смысловые отношения в тексте',2:'Лексическое значение слова',3:'Стилистический анализ текста',4:'Орфоэпические нормы',5:'Паронимы и лексические нормы',6:'Лексическая сочетаемость',7:'Морфологические нормы',8:'Синтаксические нормы',9:'Правописание корней',10:'Правописание приставок',11:'Правописание суффиксов',12:'Правописание окончаний и суффиксов',13:'Слитное и раздельное написание НЕ',14:'Слитное, дефисное и раздельное написание',15:'Н и НН',16:'Пунктуация в простом предложении',17:'Обособленные члены предложения',18:'Вводные слова и обращения',19:'Пунктуация в сложноподчинённом предложении',20:'Пунктуация в сложном предложении',21:'Пунктуационный анализ',22:'Содержание текста',23:'Типы речи',24:'Лексический анализ',25:'Средства связи предложений',26:'Средства выразительности',27:'Сочинение по прочитанному тексту'},
'ОГЭ|Русский язык':{1:'Сжатое изложение',2:'Синтаксический анализ',3:'Пунктуационный анализ',4:'Анализ словосочетания',5:'Орфографический анализ',6:'Анализ содержания текста',7:'Средства выразительности',8:'Лексический анализ',9:'Сочинение-рассуждение'},
'ЕГЭ|Английский язык':{1:'Аудирование: соответствие высказываний',2:'Аудирование: выбор ответа',3:'Аудирование: понимание деталей',10:'Чтение: соответствие заголовков',11:'Чтение: восстановление текста',12:'Чтение: понимание деталей',19:'Грамматические формы',25:'Словообразование',30:'Лексико-грамматический выбор',37:'Электронное письмо',38:'Развёрнутое письменное высказывание'},
'ОГЭ|Английский язык':{1:'Аудирование: основное содержание',6:'Аудирование: запрашиваемая информация',12:'Чтение: основное содержание',20:'Чтение: запрашиваемая информация',29:'Грамматические формы',35:'Электронное письмо',36:'Чтение текста вслух',37:'Диалог-расспрос',38:'Монологическое высказывание'},
'ЕГЭ|Обществознание':{1:'Признаки обществоведческого понятия',2:'Обобщающее понятие',3:'Классификация обществоведческих понятий',4:'Человек, общество и духовная культура',5:'Экономические институты и процессы',6:'Экономика: установление соответствия',7:'Социальные отношения и социальные группы',8:'Социальные нормы и процессы',9:'Политика и власть',10:'Политическая система и государство',11:'Право: выбор верных суждений',12:'Правовые отношения и отрасли права',13:'Конституционный строй Российской Федерации',14:'Полномочия органов государственной власти',15:'Право: установление соответствия',16:'Правовая ситуация и применение норм',17:'Поиск информации в обществоведческом тексте',18:'Объяснение положений текста',19:'Примеры, иллюстрирующие положения текста',20:'Формулирование суждений на основе текста',21:'Анализ графика спроса и предложения',22:'Комплексная задача по социальной ситуации',23:'Конституционные обязанности и ценности',24:'Сложный план по обществоведческой теме',25:'Обоснование позиции и примеры'},
'ОГЭ|Обществознание':{1:'Признаки обществоведческого понятия',2:'Человек и общество',3:'Сфера духовной культуры',4:'Экономика и хозяйственная деятельность',5:'Социальная сфера и социальные отношения',6:'Финансовая грамотность по изображению',7:'Экономические отношения',8:'Социальные нормы и отклоняющееся поведение',9:'Политика, государство и гражданское общество',10:'Право и правовые отношения',11:'Анализ обществоведческой ситуации',12:'Анализ статистических данных: выводы и предположение',13:'Конституционный строй и органы власти',14:'Права, обязанности и юридическая ответственность',15:'Установление соответствия понятий и примеров',16:'Выбор обобщающего понятия',17:'Поиск информации в тексте',18:'Составление плана текста',19:'Объяснение авторской позиции',20:'Примеры к положениям текста',21:'Аргументированный ответ по проблеме текста',22:'Практическая социальная задача',23:'Формулирование суждений и объяснений',24:'Развёрнутый ответ с опорой на обществоведческие знания'},
'ЕГЭ|История':{1:'Хронологическая последовательность событий',2:'Соответствие событий и дат',3:'Исторические термины',4:'Исторические личности и события',5:'Соответствие фактов, процессов и явлений',6:'Анализ письменного исторического источника',7:'Памятники культуры и их характеристики',8:'История Великой Отечественной войны',9:'Работа с исторической картой: событие',10:'Работа с исторической картой: территория',11:'Работа с исторической картой: факты',12:'Анализ исторического источника',13:'Характеристика периода по источнику',14:'Поиск информации в историческом источнике',15:'Атрибуция памятника культуры',16:'Историко-культурный контекст',17:'Причинно-следственные связи',18:'Аргументация исторической позиции',19:'Определение исторического понятия',20:'Сравнение исторических событий или процессов',21:'Развёрнутая историческая задача'}
};
function taskEssence(exam,subject,number,part){const n=parseInt(String(number).replace(/\D/g,''),10),exact=taskEssences[`${exam}|${subject}`]?.[n];if(exact)return exact;if(subject==='Литература')return part==='Часть 1'?'Анализ художественного текста':'Развёрнутый анализ или сочинение';if(subject==='Информатика')return n<=10?'Информационные модели, логика и алгоритмы':n<=20?'Программирование и обработка данных':'Программирование повышенной сложности';if(subject==='Физика')return n<=12?'Применение физических законов':n<=20?'Расчётная физическая задача':'Развёрнутая задача с обоснованием';if(subject==='Химия')return n<=17?'Строение, свойства веществ и реакции':n<=28?'Расчёты и химические превращения':'Развёрнутая расчётная задача';if(subject==='Биология')return n<=15?'Биологические понятия и процессы':n<=22?'Анализ биологической информации':'Развёрнутая биологическая задача';if(subject==='История')return n<=12?'Факты, хронология, карта или источник':'Анализ источника и развёрнутый ответ';if(subject==='География')return n<=20?'Географические понятия, карта и данные':'Расчёты и анализ географической информации';if(subject==='Обществознание')return n<=16?'Понятия и социальные ситуации':'Анализ источника и развёрнутый ответ';if(subject==='Английский язык')return String(number).startsWith('У')?'Устная речь':part==='Часть 1'?'Аудирование, чтение, грамматика или лексика':'Письменная речь';return part==='Часть 1'?'Предметные знания и способы действий':'Развёрнутая задача с обоснованием решения'}

let data = load();
const $=id=>document.getElementById(id); const filters=['yearFilter','examFilter','subjectFilter','teacherFilter'];
function num(v){if(v===''||v==null)return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null}
function clean(rows){return rows.filter(x=>!(x.exam==='ЕГЭ'&&/(математика.*баз|базов.*математ)/i.test(x.subject||'')))}
function load(){try{const saved=JSON.parse(localStorage.getItem('gia1273:data'));if(!saved)return clean(demo);const key=x=>`${x.year}|${x.exam}|${x.subject}`,defaults=new Map(demo.map(x=>[key(x),x])),merged=saved.map(x=>{const authoritative=defaults.get(key(x));return {...x,city:x.city??authoritative?.city??null,participants:authoritative?.participants??x.participants??null}}),present=new Set(merged.map(key));demo.forEach(x=>{if(!present.has(key(x)))merged.push(x)});const cleaned=clean(merged);localStorage.setItem('gia1273:data',JSON.stringify(cleaned));return cleaned}catch{return clean(demo)}}
function save(){localStorage.setItem('gia1273:data',JSON.stringify(data))}
function unique(key){return [...new Set(data.map(d=>d[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ru',{numeric:true}))}
function fillSelect(id,vals,all=true){const el=$(id),old=el.value;el.innerHTML=(all?'<option value="Все">Все</option>':'')+vals.map(v=>`<option>${esc(v)}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old}
function yearChoice(id,rows){const years=[...new Set(rows.map(x=>x.year))].sort(),el=$(id),old=el.value;el.innerHTML=years.map(y=>`<option>${y}</option>`).join('');el.value=years.includes(old)?old:years.at(-1);return el.value}
function periodChoice(id,rows){const years=[...new Set(rows.map(x=>x.year))].sort(),el=$(id),old=el.value||'Все годы';el.innerHTML='<option>Все годы</option>'+years.map(y=>`<option>${y}</option>`).join('');el.value=old==='Все годы'||years.includes(old)?old:'Все годы';return el.value}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function current(){return data.filter(d=>(['Все',''].includes($('yearFilter').value)||d.year===$('yearFilter').value)&&(['Все',''].includes($('examFilter').value)||d.exam===$('examFilter').value)&&(['Все',''].includes($('subjectFilter').value)||d.subject===$('subjectFilter').value)&&(['Все',''].includes($('teacherFilter').value)||d.teacher===$('teacherFilter').value))}
function avg(arr,key){const a=arr.map(x=>x[key]).filter(x=>x!=null);return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
function scoreMax(rows){return rows.length&&rows.every(x=>x.exam==='ОГЭ')?5:100}
function fmt(v,d=1){return v==null?'—':v.toLocaleString('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d})}
function render(){fillSelect('yearFilter',unique('year'));fillSelect('subjectFilter',unique('subject'));fillSelect('teacherFilter',unique('teacher'));const rows=current(),oge=rows.length&&rows.every(x=>x.exam==='ОГЭ');$('schoolCityPanel').hidden=oge;$('gapPanel').hidden=oge;renderKpis(rows);renderTopics();renderTaskAnalysis();renderYearComparison(rows);if(!oge)renderSchoolCity(rows);renderBars(rows);renderTable(rows)}
function topicGrade(subject,name){const embedded=name.match(/,\s*(\d+(?:[–-]\d+)?)\s*класс/i);return {name:embedded?name.slice(0,embedded.index):name,grade:embedded?`${embedded[1]} класс`:topicGrades[name]||topicDefaults[subject]||'5–11 классы'}}
function renderTopics(){const subject=$('subjectFilter').value,panel=$('topicAnalysis');if(!subject||subject==='Все'){panel.hidden=true;return}panel.hidden=false;$('topicTitle').textContent=`Ключевые темы: ${subject}`;const item=topicAnalytics[subject];if(!item){$('topicContent').innerHTML='<div class="topicEmpty">В предоставленных материалах нет поэлементного анализа по этому предмету.</div>';return}const showValue=value=>`${String(value).replace('.',',')}%`;const list=(title,rows,type)=>`<div class="topicColumn ${type}"><h3>${title}</h3><ol>${rows.map(([name,value])=>{const t=topicGrade(subject,name);return `<li><span class="topicName"><span>${esc(t.name)}</span><small class="gradeTag">${esc(t.grade)}</small></span><strong>${showValue(value)}</strong></li>`}).join('')}</ol></div>`;$('topicContent').innerHTML=`<div class="topicGrid">${list('Ключевые дефициты',item.deficits,'deficit')}${list('5 наиболее успешных тем и разделов',item.success,'success')}</div>`}
function taskTone(v){return v<50?'bad':v<70?'mid':'good'}
function renderTaskAnalysis(){const subject=$('subjectFilter').value,exam=$('examFilter').value,panel=$('taskAnalysis');if(!subject||subject==='Все'||!exam||exam==='Все'){panel.hidden=true;return}panel.hidden=false;const years=Object.keys(taskAnalytics).filter(y=>taskAnalytics[y]?.[exam]?.[subject]).sort(),displayYear=years.at(-1),item=taskAnalytics?.[displayYear]?.[exam]?.[subject];$('taskTitle').textContent=`Выполнение заданий: ${subject}`;if(!item?.tasks?.length){$('taskSource').textContent=`${exam}`;$('weakTasks').innerHTML='<div class="topicEmpty">По выбранному предмету нет поэлементных данных.</div>';$('allTasks').innerHTML='';$('criteriaTasks').innerHTML='';$('taskConclusion').innerHTML='';return}const officialParticipants=data.find(x=>x.year===displayYear&&x.exam===exam&&x.subject===subject)?.participants??item.participants;$('taskSource').textContent=`${exam}, ${displayYear} · участников: ${officialParticipants}`;const weak=[...item.tasks].filter(x=>x.percent!=null).sort((a,b)=>a.percent-b.percent).slice(0,8);$('weakTasks').innerHTML=weak.map(x=>{const essence=taskEssence(exam,subject,x.number,x.part);return `<div class="taskRow"><span class="taskNumber">№ ${esc(x.number)}</span><span class="taskFormat"><b class="taskEssence">${esc(essence)}</b><br>${esc(x.part)} · ${esc(x.format)}</span><strong class="taskPercent ${taskTone(x.percent)}">${fmt(x.percent)}%</strong></div>`}).join('');const groups={};item.tasks.forEach(x=>(groups[x.part]??=[]).push(x));$('allTasks').innerHTML=Object.entries(groups).map(([part,tasks])=>`<div class="partGroup"><h4>${esc(part)}</h4><div class="taskChips">${tasks.map(x=>{const essence=taskEssence(exam,subject,x.number,x.part);return `<span class="taskChip ${taskTone(x.percent)}" title="${esc(essence)}; ${esc(x.format)}; ответов в протоколе: ${x.participants}"><b>№ ${esc(x.number)}</b><small>${fmt(x.percent)}%</small></span>`}).join('')}</div><div class="formatLegend">${esc(tasks[0].format)} · наведите на номер, чтобы увидеть краткое содержание</div></div>`).join('');renderCriteriaTasks(exam,subject,item);renderTaskConclusion(exam,subject,displayYear,item)}
function renderCriteriaTasks(exam,subject,item){const tasks=item.tasks.filter(t=>t.criteria?.length>1);if(!tasks.length){$('criteriaTasks').innerHTML='';return}$('criteriaTasks').innerHTML=`<h3>Выполнение заданий по критериям</h3><p>Показано, какая доля максимального балла набрана по каждому критерию и какая доля баллов утрачена.</p><div class="criteriaGrid">${tasks.map(t=>`<article class="criteriaCard"><div class="criteriaTitle"><b>№ ${esc(t.number)} — ${esc(taskEssence(exam,subject,t.number,t.part))}</b><strong>${fmt(t.percent)}% баллов</strong></div>${t.criteria.map(c=>`<div class="criterionRow"><span><b>${esc(c.code)}.</b> ${esc(c.label)}</span><span class="criterionValues"><em class="done">${fmt(c.percent)}% выполнено</em><em class="lost">${fmt(c.deficit)}% дефицит</em></span></div>`).join('')}</article>`).join('')}</div>`}
function renderTaskConclusion(exam,subject,year,item){const vals=item.tasks.map(t=>t.percent).filter(v=>v!=null);if(!vals.length){$('taskConclusion').innerHTML='';return}const mean=vals.reduce((a,b)=>a+b,0)/vals.length,low=vals.filter(v=>v<50).length,high=vals.filter(v=>v>=70).length,weak=[...item.tasks].filter(t=>t.percent!=null).sort((a,b)=>a.percent-b.percent)[0];$('taskConclusion').innerHTML=`<strong>Общий вывод за ${year} год.</strong> Средний процент выполнения заданий — ${fmt(mean)}%. Устойчивый результат показан по ${high} из ${vals.length} заданий (не менее 70%); зона риска — ${low} заданий (менее 50%). Наиболее проблемное — № ${esc(weak.number)} «${esc(taskEssence(exam,subject,weak.number,weak.part))}» (${fmt(weak.percent)}%).`}
function renderKpis(rows){const years=[...new Set(rows.map(x=>x.year))].sort(),latest=years.at(-1),last=rows.filter(x=>x.year===latest),school=avg(last,'school'),city=avg(last,'city'),gap=school!=null&&city!=null?school-city:null,exam=$('examFilter').value,allSubjects=$('subjectFilter').value==='Все',resultCount=last.reduce((s,x)=>s+(x.participants||0),0),participants=allSubjects?(uniqueParticipants[exam]?.[latest]??null):resultCount,subjectsAbove=last.filter(x=>x.school!=null&&x.city!=null&&x.school>x.city).length,oge=rows.length&&rows.every(x=>x.exam==='ОГЭ'),series=(fn)=>years.map(y=>`${y}: ${fn(rows.filter(x=>x.year===y),y)}`).join(' · '),base=[[oge?'Средняя отметка школы':'Средний балл школы',fmt(school),series(r=>fmt(avg(r,'school'))) ],['Участники',participants||'—',series((r,y)=>allSubjects?(uniqueParticipants[exam]?.[y]??'—'):(r.reduce((s,x)=>s+(x.participants||0),0)||'—'))]],resultCard=['Экзаменационные результаты',resultCount||'—',series(r=>r.reduce((s,x)=>s+(x.participants||0),0)||'—')],cityCards=[['Средний балл Москвы',fmt(city),series(r=>fmt(avg(r,'city'))) ],['Разрыв с городом',gap==null?'—':`${gap>=0?'+':''}${fmt(gap)}`,series(r=>{const a=avg(r,'school'),b=avg(r,'city');return a==null||b==null?'—':`${a-b>=0?'+':''}${fmt(a-b)}`})],['Выше города',subjectsAbove,series(r=>`${r.filter(x=>x.school!=null&&x.city!=null&&x.school>x.city).length}/${r.filter(x=>x.city!=null).length}`)]],values=oge?[...base,...(allSubjects?[resultCard]:[])]:[base[0],...cityCards.slice(0,2),base[1],...(allSubjects?[resultCard]:[]),cityCards[2]];$('kpis').innerHTML=values.map(v=>`<div class="kpi"><span>${v[0]}</span><strong>${v[1]}</strong><small>${v[2]}</small></div>`).join('')}
function renderYearComparison(rows){const period=periodChoice('yearComparisonPeriodFilter',rows),shown=period==='Все годы'?rows:rows.filter(x=>x.year===period),years=[...new Set(shown.map(x=>x.year))].sort(),subjects=[...new Set(shown.map(x=>x.subject))].sort((a,b)=>a.localeCompare(b,'ru'));if(!years.length||!subjects.length)return empty('yearComparisonChart');const colors=['#8aa7c4','#ef7d24','#123a66','#13866f','#9b6dcc'],max=scoreMax(shown),step=max===5?1:20;$('yearsLegend').innerHTML=years.map((yr,i)=>`<i style="background:${colors[i%colors.length]}"></i>${yr}`).join(' ');const W=Math.max(980,subjects.length*105),H=400,p={l:45,r:20,t:25,b:110},y=v=>p.t+(max-v)*(H-p.t-p.b)/max,group=(W-p.l-p.r)/subjects.length,bar=Math.min(22,(group-12)/years.length);let g='';for(let t=0;t<=max;t+=step)g+=`<line class="axis" x1="${p.l}" x2="${W-p.r}" y1="${y(t)}" y2="${y(t)}"/><text class="label" x="8" y="${y(t)+4}">${t}</text>`;subjects.forEach((s,si)=>{const center=p.l+group*(si+.5);years.forEach((yr,yi)=>{const row=shown.find(x=>x.subject===s&&x.year===yr),v=row?.school;if(v==null)return;const x=center-(years.length*bar)/2+yi*bar;g+=`<rect x="${x}" y="${y(v)}" width="${bar-3}" height="${H-p.b-y(v)}" rx="3" fill="${colors[yi%colors.length]}"/><text class="value" text-anchor="middle" x="${x+(bar-3)/2}" y="${y(v)-5}">${fmt(v)}</text>`});g+=`<text class="label" text-anchor="end" transform="translate(${center+4},${H-p.b+15}) rotate(-48)">${esc(s)}</text>`});$('yearComparisonChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" ${years.length>1?`style="min-width:${W}px"`:''} role="img" aria-label="Сравнение результатов школы по предметам и годам">${g}</svg>`}
function renderSchoolCity(rows){const period=periodChoice('schoolCityYearFilter',rows),all=period==='Все годы',items=(all?rows:rows.filter(x=>x.year===period)).filter(x=>x.school!=null&&x.city!=null).sort((a,b)=>a.subject.localeCompare(b.subject,'ru')||a.year.localeCompare(b.year));if(!items.length)return empty('schoolCityChart');const W=Math.max(1080,items.length*96),H=390,p={l:45,r:20,t:25,b:115},y=v=>p.t+(100-v)*(H-p.t-p.b)/100,group=(W-p.l-p.r)/items.length,bar=Math.min(25,(group-16)/2);let g='';for(let t=0;t<=100;t+=20)g+=`<line class="axis" x1="${p.l}" x2="${W-p.r}" y1="${y(t)}" y2="${y(t)}"/><text class="label" x="8" y="${y(t)+4}">${t}</text>`;items.forEach((row,i)=>{const center=p.l+group*(i+.5),pairs=[[row.school,'#123a66'],[row.city,'#ef7d24']];pairs.forEach(([v,color],j)=>{const x=center-bar+(j*bar);g+=`<rect x="${x}" y="${y(v)}" width="${bar-3}" height="${H-p.b-y(v)}" rx="3" fill="${color}"/><text class="value" text-anchor="middle" x="${x+(bar-3)/2}" y="${y(v)-5}">${fmt(v)}</text>`});const label=all?`${row.subject} · ${row.year}`:row.subject;g+=`<text class="label" text-anchor="end" transform="translate(${center+4},${H-p.b+15}) rotate(-48)">${esc(label)}</text>`});$('schoolCityChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" style="min-width:${W}px" role="img" aria-label="Сравнение средних баллов школы и Москвы по предметам: ${period}">${g}</svg>`}
function renderBars(rows){const gapPeriod=periodChoice('gapYearFilter',rows),allGap=gapPeriod==='Все годы',selectedGap=allGap?rows:rows.filter(x=>x.year===gapPeriod),gapRows=allGap?selectedGap.map(x=>({...x,year:'Все годы',subject:`${x.subject} · ${x.year}`})):selectedGap,participantsPeriod=periodChoice('participantsPeriodFilter',rows),participantsRows=participantsPeriod==='Все годы'?rows:rows.filter(x=>x.year===participantsPeriod);yearMetricChart('gapChart',null,gapRows,x=>x.school!=null&&x.city!=null?x.school-x.city:null,true);yearMetricChart('participantsChart','participantsLegend',participantsRows,x=>x.participants,false)}
function yearMetricChart(id,legendId,rows,getValue,signed){const years=[...new Set(rows.map(x=>x.year))].sort(),subjects=[...new Set(rows.map(x=>x.subject))].sort((a,b)=>a.localeCompare(b,'ru')),colors=['#8aa7c4','#ef7d24','#123a66','#13866f','#9b6dcc'];if(!years.length||!subjects.length)return empty(id);if(legendId)$(legendId).innerHTML=years.map((yr,i)=>`<i style="background:${colors[i%colors.length]}"></i>${yr}`).join(' ');const values=rows.map(getValue).filter(v=>v!=null),limit=signed?Math.max(...values.map(Math.abs),1):Math.max(...values,1),W=Math.max(980,subjects.length*105),H=400,p={l:50,r:20,t:25,b:110},zero=signed?p.t+(H-p.t-p.b)/2:H-p.b,y=v=>signed?zero-v*((H-p.t-p.b)/2)/limit:p.t+(limit-v)*(H-p.t-p.b)/limit,group=(W-p.l-p.r)/subjects.length,bar=Math.min(22,(group-12)/years.length);let g='';if(signed){g+=`<line class="axis" x1="${p.l}" x2="${W-p.r}" y1="${zero}" y2="${zero}"/><text class="label" x="12" y="${zero+4}">0</text>`}else for(let t=0;t<=limit;t+=Math.max(1,Math.ceil(limit/5/10)*10))g+=`<line class="axis" x1="${p.l}" x2="${W-p.r}" y1="${y(t)}" y2="${y(t)}"/><text class="label" x="5" y="${y(t)+4}">${t}</text>`;subjects.forEach((s,si)=>{const center=p.l+group*(si+.5);years.forEach((yr,yi)=>{const row=rows.find(x=>x.subject===s&&x.year===yr),v=row?getValue(row):null;if(v==null)return;const x=center-(years.length*bar)/2+yi*bar,yy=signed&&v<0?zero: y(v),height=Math.abs((signed?zero:y(0))-y(v));g+=`<rect x="${x}" y="${yy}" width="${bar-3}" height="${Math.max(1,height)}" rx="3" fill="${signed&&v<0?'#c94949':colors[yi%colors.length]}"/><text class="value" text-anchor="middle" x="${x+(bar-3)/2}" y="${signed&&v<0?yy+height+13:yy-5}">${signed&&v>0?'+':''}${fmt(v,signed?1:0)}</text>`});g+=`<text class="label" text-anchor="end" transform="translate(${center+4},${H-p.b+15}) rotate(-48)">${esc(s)}</text>`});$(id).innerHTML=`<svg viewBox="0 0 ${W} ${H}" ${years.length>1?`style="min-width:${W}px"`:''}>${g}</svg>`}
function barChart(id,vals,signed){if(!vals.length)return empty(id);vals=vals.sort((a,b)=>b.value-a.value);const W=650,H=Math.max(250,vals.length*30),left=180,right=45,top=10;const max=Math.max(...vals.map(v=>Math.abs(v.value)),1),zero=signed?(left+(W-left-right)/2):left,scale=(W-left-right)/(signed?2:1)/max;let g=vals.map((v,i)=>{const yy=top+i*30,w=Math.abs(v.value)*scale,x=signed&&v.value<0?zero-w:zero,color=v.value>=0?'#13866f':'#c94949';return `<text class="label" text-anchor="end" x="${left-8}" y="${yy+17}">${esc(v.label.length>24?v.label.slice(0,23)+'…':v.label)}</text><rect x="${x}" y="${yy+5}" width="${Math.max(1,w)}" height="16" rx="4" fill="${signed?color:'#123a66'}"/><text class="value" x="${signed&&v.value<0?x-5:x+w+5}" text-anchor="${signed&&v.value<0?'end':'start'}" y="${yy+17}">${signed&&v.value>0?'+':''}${fmt(v.value,signed?1:0)}</text>`}).join('');if(signed)g+=`<line class="axis" x1="${zero}" x2="${zero}" y1="0" y2="${H}"/>`;$(id).innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMinYMin meet">${g}</svg>`}
function renderTable(rows){const period=periodChoice('tableYearFilter',rows),shown=period==='Все годы'?rows:rows.filter(x=>x.year===period),ordered=shown.sort((a,b)=>b.year.localeCompare(a.year)||a.subject.localeCompare(b.subject,'ru')),oge=ordered.length&&ordered.every(x=>x.exam==='ОГЭ');$('resultsHead').innerHTML=oge?'<tr><th>Год</th><th>Предмет</th><th>Экзамен</th><th>Участники</th><th>Средняя отметка</th></tr>':'<tr><th>Год</th><th>Предмет</th><th>Экзамен</th><th>Участники</th><th>Школа</th><th>Город</th><th>Разрыв</th><th>Место</th><th>Педагог</th></tr>';$('resultsBody').innerHTML=ordered.length?ordered.map(x=>{if(oge)return `<tr><td><strong>${x.year}</strong></td><td><strong>${esc(x.subject)}</strong></td><td>${x.exam}</td><td>${x.participants??'—'}</td><td>${fmt(x.school)}</td></tr>`;const gap=x.school!=null&&x.city!=null?x.school-x.city:null;return `<tr><td><strong>${x.year}</strong></td><td><strong>${esc(x.subject)}</strong></td><td>${x.exam}</td><td>${x.participants??'—'}</td><td>${fmt(x.school)}</td><td>${fmt(x.city)}</td><td><span class="pill ${gap!=null&&gap<0?'bad':''}">${gap==null?'—':`${gap>=0?'+':''}${fmt(gap)}`}</span></td><td>${x.rank?`${x.rank} из ${x.total||'—'}`:'—'}</td><td>${esc(x.teacher||'—')}</td></tr>`}).join(''):`<tr><td colspan="${oge?5:9}">Нет данных по выбранным фильтрам</td></tr>`}
function empty(id){$(id).innerHTML='<div class="empty">Нет данных</div>'}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const h=lines.shift().split(sep).map(x=>x.trim().toLowerCase());const names={год:'year',year:'year',экзамен:'exam',exam:'exam',предмет:'subject',subject:'subject','балл школы':'school',school:'school','балл города':'city',city:'city',участники:'participants',participants:'participants',место:'rank',rank:'rank','всего школ':'total',total:'total',педагог:'teacher',teacher:'teacher'};return lines.filter(Boolean).map(line=>{const c=line.split(sep).map(x=>x.trim().replace(/^"|"$/g,'')),o={};h.forEach((x,i)=>o[names[x]||x]=c[i]);['school','city','participants','rank','total'].forEach(k=>o[k]=num(o[k]));o.year=String(o.year||'');return o}).filter(x=>x.year&&x.subject)}
function download(name,text,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
filters.forEach(id=>$(id).addEventListener('change',render));$('resetFilters').onclick=()=>{['yearFilter','subjectFilter','teacherFilter'].forEach(id=>$(id).value='Все');$('examFilter').value='ЕГЭ';render()};$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=f.name.endsWith('.json')?JSON.parse(await f.text()):parseCSV(await f.text());if(!Array.isArray(parsed)||!parsed.length)throw Error();data=clean(parsed);save();$('status').textContent=`Загружено строк: ${data.length}`;render()}catch{$('status').textContent='Не удалось прочитать файл. Используйте шаблон CSV.'}};$('downloadTemplate').onclick=()=>download('Шаблон_данных_ГИА.csv','Год;Экзамен;Предмет;Балл школы;Балл города;Участники;Место;Всего школ;Педагог\n2027;ЕГЭ;Русский язык;72,4;70,1;150;55;285;ФИО');$('exportData').onclick=()=>download('Данные_ГИА_1273.json',JSON.stringify(data,null,2),'application/json');$('restoreDemo').onclick=()=>{data=clean(demo);save();render();$('status').textContent='Исходные данные восстановлены'};
$('schoolCityYearFilter').addEventListener('change',()=>renderSchoolCity(current()));$('gapYearFilter').addEventListener('change',()=>renderBars(current()));$('tableYearFilter').addEventListener('change',()=>renderTable(current()));$('yearComparisonPeriodFilter').addEventListener('change',()=>renderYearComparison(current()));$('participantsPeriodFilter').addEventListener('change',()=>renderBars(current()));
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'replace_gia_data',title:'Обновить данные ГИА',description:'Заменяет данные дашборда нормализованным массивом результатов ГИА.',inputSchema:{type:'object',properties:{rows:{type:'array',items:{type:'object',properties:{year:{type:'string'},exam:{type:'string'},subject:{type:'string'},school:{type:'number'},city:{type:'number'},participants:{type:'number'}},required:['year','exam','subject','school']}}},required:['rows'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({rows}){if(!Array.isArray(rows)||!rows.length)throw new Error('rows must not be empty');data=clean(rows);save();render();return {updated:data.length}}})}
render();
